### ISSUE TITLE
インポート時に一部エラーが発生する

### ISSUE THREAD

**Issue by hibiki31** [hibiki31/hinagiku-viewer#19]
```
2021-08-13 08:36:13 - INFO - ライブラリにインポート: /opt/data/book_library/4e166322-0edc-4396-ac92-effcc43aa7bc.zip
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NumericValueOutOfRange: integer out of range


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/app/worker.py", line 89, in <module>
    task_library_import(db=db, user_id=user_id)
  File "/opt/app/tasks/library_import.py", line 53, in main
    book_import(send_book, user_model, db)
  File "/opt/app/tasks/library_import.py", line 156, in book_import
    db.commit()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1428, in commit
    self._transaction.commit(_to_root=self.future)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3298, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3438, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3398, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 242, in save_obj
    _emit_insert_statements(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1094, in _emit_insert_statements
    c = connection._execute_20(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1583, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1452, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1814, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1995, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.NumericValueOutOfRange) integer out of range

[SQL: INSERT INTO book (uuid, user_id, size, sha1, page, add_date, file_date, import_file_name, title, series_no, library_id, genre_id, publisher_id, series_id, is_shered, state) VALUES (%(uuid)s, %(user_id)s, %(size)s, %(sha1)s, %(page)s, %(add_date)s, %(file_date)s, %(import_file_name)s, %(title)s, %(series_no)s, %(library_id)s, %(genre_id)s, %(publisher_id)s, %(series_id)s, %(is_shered)s, %(state)s)]
[parameters: {'uuid': 'b43b77d1-615d-4708-ba82-ceb2975774b4', 'user_id': 'akane', 'size': 3943765102, 'sha1': 'b789cac7b4f71981fe15e3f87c9bba470857537e', 'page': 360, 'add_date': datetime.datetime(2021, 4, 7, 15, 21, 33, 23836), 'file_date': datetime.datetime(2021, 1, 15, 4, 44, 54, 557206), 'import_file_name': '******', 'series_no': None, 'library_id': 1, 'genre_id': None, 'publisher_id': None, 'series_id': None, 'is_shered': False, 'state': None}]
(Background on this error at: https://sqlalche.me/e/14/9h9h)
```

**Comment by hibiki31** [comment]
sizeはInt型だと足りない
