### ISSUE TITLE
本を開いた際にエラーが発生する

### ISSUE THREAD

**Issue by hibiki31** [hibiki31/hinagiku-viewer#38]
```
api-1  | [2024-05-05 06:36:54 +0000] [14] [ERROR] Exception in ASGI application
api-1  | Traceback (most recent call last):
api-1  |   File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 98, in receive
api-1  |     return self.receive_nowait()
api-1  |            ^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
api-1  |     raise WouldBlock
api-1  | anyio.WouldBlock
api-1  |
api-1  | During handling of the above exception, another exception occurred:
api-1  |
api-1  | Traceback (most recent call last):
api-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 78, in call_next
api-1  |     message = await recv_stream.receive()
api-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 118, in receive
api-1  |     raise EndOfStream
api-1  | anyio.EndOfStream
api-1  |
api-1  | During handling of the above exception, another exception occurred:
api-1  |
api-1  | Traceback (most recent call last):
api-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
api-1  |     result = await app(  # type: ignore[func-returns-value]
api-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
api-1  |     return await self.app(scope, receive, send)
api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 289, in __call__
api-1  |     await super().__call__(scope, receive, send)
api-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
api-1  |     await self.middleware_stack(scope, receive, send)
api-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
api-1  |     raise exc
api-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
api-1  |     await self.app(scope, receive, _send)
api-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
api-1  |     response = await self.dispatch_func(request, call_next)
api-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/opt/app/main.py", line 79, in db_session_middleware
api-1  |     response = await call_next(request)
api-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
api-1  |     raise app_exc
api-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
api-1  |     await self.app(scope, receive_or_disconnect, send_no_error)
api-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
api-1  |     await self.app(scope, receive, send)
api-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
api-1  |     raise exc
api-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
api-1  |     await self.app(scope, receive, sender)
api-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
api-1  |     raise e
api-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
api-1  |     await self.app(scope, receive, send)
api-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
api-1  |     await route.handle(scope, receive, send)
api-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
api-1  |     await self.app(scope, receive, send)
api-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
api-1  |     response = await func(request)
api-1  |                ^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
api-1  |     raw_response = await run_endpoint_function(
api-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
api-1  |     return await run_in_threadpool(dependant.call, **values)
api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
api-1  |     return await anyio.to_thread.run_sync(func, *args)
api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
api-1  |     return await get_asynclib().run_sync_in_worker_thread(
api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
api-1  |     return await future
api-1  |            ^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
api-1  |     result = context.run(func, *args)
api-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/opt/app/media/router.py", line 134, in media_books_uuid_page
api-1  |     image_convertor(glob.glob(original_file)[0], cache_file, to_height=height, quality=85)
api-1  |   File "/opt/app/mixins/convertor.py", line 288, in image_convertor
api-1  |     img = Image.open(src_path).convert('RGB')
api-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/PIL/Image.py", line 911, in convert
api-1  |     self.load()
api-1  |   File "/usr/local/lib/python3.11/site-packages/PIL/ImageFile.py", line 266, in load
api-1  |     raise OSError(msg)
api-1  | OSError: image file is truncated (2 bytes not processed)
api-1  | [2024-05-05 06:36:54 +0000] [9] [ERROR] Exception in ASGI application
api-1  | Traceback (most recent call last):
api-1  |   File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 98, in receive
api-1  |     return self.receive_nowait()
api-1  |            ^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
api-1  |     raise WouldBlock
api-1  | anyio.WouldBlock
api-1  |
api-1  | During handling of the above exception, another exception occurred:
api-1  |
api-1  | Traceback (most recent call last):
api-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 78, in call_next
api-1  |     message = await recv_stream.receive()
api-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 118, in receive
api-1  |     raise EndOfStream
api-1  | anyio.EndOfStream
api-1  |
api-1  | During handling of the above exception, another exception occurred:
api-1  |
api-1  | Traceback (most recent call last):
api-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
api-1  |     result = await app(  # type: ignore[func-returns-value]
api-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
api-1  |     return await self.app(scope, receive, send)
api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 289, in __call__
api-1  |     await super().__call__(scope, receive, send)
api-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
api-1  |     await self.middleware_stack(scope, receive, send)
api-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
api-1  |     raise exc
api-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
api-1  |     await self.app(scope, receive, _send)
api-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
api-1  |     response = await self.dispatch_func(request, call_next)
api-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/opt/app/main.py", line 79, in db_session_middleware
api-1  |     response = await call_next(request)
api-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
api-1  |     raise app_exc
api-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
api-1  |     await self.app(scope, receive_or_disconnect, send_no_error)
api-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
api-1  |     await self.app(scope, receive, send)
api-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
api-1  |     raise exc
api-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
api-1  |     await self.app(scope, receive, sender)
api-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
api-1  |     raise e
api-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
api-1  |     await self.app(scope, receive, send)
api-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
api-1  |     await route.handle(scope, receive, send)
api-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
api-1  |     await self.app(scope, receive, send)
api-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
api-1  |     response = await func(request)
api-1  |                ^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
api-1  |     raw_response = await run_endpoint_function(
api-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
api-1  |     return await run_in_threadpool(dependant.call, **values)
api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
api-1  |     return await anyio.to_thread.run_sync(func, *args)
api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
api-1  |     return await get_asynclib().run_sync_in_worker_thread(
api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
api-1  |     return await future
api-1  |            ^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
api-1  |     result = context.run(func, *args)
api-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/opt/app/media/router.py", line 134, in media_books_uuid_page
api-1  |     image_convertor(glob.glob(original_file)[0], cache_file, to_height=height, quality=85)
api-1  |   File "/opt/app/mixins/convertor.py", line 288, in image_convertor
api-1  |     img = Image.open(src_path).convert('RGB')
api-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1  |   File "/usr/local/lib/python3.11/site-packages/PIL/Image.py", line 911, in convert
api-1  |     self.load()
api-1  |   File "/usr/local/lib/python3.11/site-packages/PIL/ImageFile.py", line 266, in load
api-1  |     raise OSError(msg)
api-1  | OSError: image file is truncated (2 bytes not processed)
```

**Comment by hibiki31** [comment]
ファイルが大きすぎるから発生するエラー
